import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
<Script async src="https://www.googletagmanager.com/gtag/js?id=G-349WXKM3WE"></Script>
<Script>
  {`
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-349WXKM3WE');
  `}
</Script>

<Script type="text/javascript">
{`
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "m3k8m9cp1x");
`}
</Script>

      </head>
      <body className={inter.className}>
        {children}
        </body>
    </html>
  );
}
